# Generated by Django 4.2 on 2026-05-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("contacts", "0001_initial"),
        ("templates_engine", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_logs",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="campaigncontact",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_contacts",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaigncontact",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_assignments",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="authentication.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="templates_engine.emailtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["status"], name="idx_emaillog_status"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["campaign"], name="idx_emaillog_campaign"),
        ),
        migrations.AlterUniqueTogether(
            name="campaigncontact",
            unique_together={("campaign", "contact")},
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["status"], name="idx_campaign_status"),
        ),
    ]
