# Generated by Django 4.2 on 2026-05-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
