# Generated by Django 4.2 on 2026-05-26 06:43

import uuid

from django.db import migrations, models


def backfill_idempotency_keys(apps, schema_editor):
    Campaign = apps.get_model("campaigns", "Campaign")
    for campaign in Campaign.objects.filter(idempotency_key__isnull=True).only("id"):
        campaign.idempotency_key = uuid.uuid4()
        campaign.save(update_fields=["idempotency_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_campaign_scheduled_at_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="campaign",
            name="idempotency_key",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="launch_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="campaigncontact",
            index=models.Index(fields=["campaign"], name="idx_cc_campaign"),
        ),
        migrations.AddIndex(
            model_name="campaigncontact",
            index=models.Index(fields=["delivery_status"], name="idx_cc_delivery_status"),
        ),
        migrations.AddIndex(
            model_name="campaigncontact",
            index=models.Index(fields=["campaign", "delivery_status"], name="idx_cc_campaign_status"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["sent_at"], name="idx_emaillog_sent_at"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["campaign", "status"], name="idx_emaillog_camp_status"),
        ),
        migrations.RunPython(backfill_idempotency_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="campaign",
            name="idempotency_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
