# Generated by Django 4.2 on 2026-05-24 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                ("extra_fields", models.JSONField(blank=True, default=dict)),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_duplicate", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("stored_path", models.CharField(max_length=1000)),
                (
                    "file_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("xlsx", "XLSX"), ("xls", "XLS")],
                        max_length=10,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("valid_rows", models.IntegerField(default=0)),
                ("invalid_rows", models.IntegerField(default=0)),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="authentication.adminuser",
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to="authentication.adminuser",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "status_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="contacts.uploadedfile",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="idx_contact_email"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["email_status"], name="idx_contact_email_status"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["college"], name="idx_contact_college"),
        ),
    ]
