# Generated by Django 4.2 on 2026-05-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="tenant_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="processed_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["created_at"], name="idx_contact_created_at"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["source_file"], name="idx_contact_source_file"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant_id"], name="idx_contact_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["email_status", "college"], name="idx_contact_status_college"
            ),
        ),
    ]
