# Generated by Django 4.2 on 2026-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_tenant_id_uploadedfile_processed_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="duplicate_rows",
            field=models.IntegerField(default=0),
        ),
    ]
