# Generated by Django 4.2 on 2026-05-24 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=500)),
                (
                    "body_html",
                    models.TextField(
                        help_text="HTML body. Supports {{name}}, {{college}}, {{phone}}, {{email}} variables."
                    ),
                ),
                (
                    "body_plain",
                    models.TextField(
                        blank=True, default="", help_text="Plain text body."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="authentication.adminuser",
                    ),
                ),
            ],
            options={
                "db_table": "email_templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
