# Generated by Django 4.2 on 2026-05-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="validation_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
