# Generated by Django 4.2 on 2026-05-24 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_sent", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                ("total_pending", models.IntegerField(default=0)),
                (
                    "success_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "delivery_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("college_distribution", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Analytics",
                "verbose_name_plural": "Analytics",
                "db_table": "analytics",
                "ordering": ["-date"],
            },
        ),
    ]
