# Generated by Django 4.2 on 2026-05-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_records",
                to="campaigns.campaign",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analytics",
            unique_together={("campaign", "date")},
        ),
    ]
