# Generated by Django 4.2 on 2026-06-06 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaign_failure_reason_campaign_idempotency_key_and_more"),
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                            ("unsubscribed", "Unsubscribed"),
                            ("unknown", "Unknown / Not Confirmed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="campaigns.campaigncontact",
                    ),
                ),
            ],
            options={
                "db_table": "email_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailDeliveryStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                            ("unsubscribed", "Unsubscribed"),
                            ("unknown", "Unknown / Not Confirmed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_event_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign_contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_status_record",
                        to="campaigns.campaigncontact",
                    ),
                ),
            ],
            options={
                "db_table": "email_delivery_status",
            },
        ),
        migrations.AddIndex(
            model_name="emailevent",
            index=models.Index(
                fields=["campaign_contact", "event_type"], name="idx_ee_contact_event"
            ),
        ),
        migrations.AddIndex(
            model_name="emailevent",
            index=models.Index(fields=["created_at"], name="idx_ee_created_at"),
        ),
        migrations.AddIndex(
            model_name="emaildeliverystatus",
            index=models.Index(fields=["status"], name="idx_eds_status"),
        ),
    ]
