# Generated by Django 4.2 on 2026-05-24 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("admin", "Admin"),
                            ("viewer", "Viewer"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="adminuser",
            index=models.Index(fields=["email"], name="idx_admin_users_email"),
        ),
        migrations.AddIndex(
            model_name="adminuser",
            index=models.Index(fields=["role"], name="idx_admin_users_role"),
        ),
    ]
