# Generated by Django 4.2 on 2026-05-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email_provider",
                    models.CharField(
                        choices=[("brevo", "Brevo"), ("ses", "AWS SES")],
                        default="brevo",
                        max_length=20,
                    ),
                ),
                ("brevo_config", models.JSONField(blank=True, default=dict)),
                ("ses_config", models.JSONField(blank=True, default=dict)),
                ("campaign_defaults", models.JSONField(blank=True, default=dict)),
                (
                    "notification_preferences",
                    models.JSONField(blank=True, default=dict),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
