# Generated by Django 4.2 on 2026-06-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="gmail_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="email_provider",
            field=models.CharField(
                choices=[
                    ("brevo", "Brevo"),
                    ("ses", "AWS SES"),
                    ("gmail", "Gmail SMTP"),
                ],
                default="brevo",
                max_length=20,
            ),
        ),
    ]
